#!/usr/bin/env bash
# helpers.bash — shared bats setup for the expo-builder suite tests.
#
# Real-data principle: scripts run against REAL directories and files under
# BATS_TEST_TMPDIR; signing tests use a keystore generated by a REAL keytool.
# Only network-bound binaries (npx, gh) are PATH-shimmed with recorders — their
# real behavior is proven end-to-end by .github/workflows/expo-integration.yml.

common_setup() {
    BATS_TEST_TMPDIR="${BATS_TEST_TMPDIR:-$(mktemp -d)}"
    export BATS_TEST_TMPDIR
    SUITE_ROOT="$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)"
    export SUITE_ROOT

    export GITHUB_ENV="$BATS_TEST_TMPDIR/github.env"
    export GITHUB_OUTPUT="$BATS_TEST_TMPDIR/github.output"
    : >"$GITHUB_ENV"
    : >"$GITHUB_OUTPUT"

    export RUNNER_TEMP="$BATS_TEST_TMPDIR/runner-temp"
    mkdir -p "$RUNNER_TEMP"

    SHIM_DIR="$BATS_TEST_TMPDIR/shims"
    export SHIM_DIR
    mkdir -p "$SHIM_DIR"
    export PATH="$SHIM_DIR:$PATH"

    # A real directory standing in for the Android SDK location check.
    export ANDROID_HOME="$BATS_TEST_TMPDIR/android-sdk"
    mkdir -p "$ANDROID_HOME"
    unset ANDROID_SDK_ROOT 2>/dev/null || true
}

common_teardown() { :; }

# Create a real minimal Expo app root (package.json, app.json, node_modules/)
# and echo its path. Optional $1 overrides the directory name.
make_app_dir() {
    local name="${1:-app}"
    local dir="$BATS_TEST_TMPDIR/$name"
    mkdir -p "$dir/node_modules"
    printf '{"name":"fixture","version":"1.0.0"}\n' >"$dir/package.json"
    printf '{"expo":{"name":"fixture","slug":"fixture","version":"1.2.3"}}\n' >"$dir/app.json"
    printf '%s\n' "$dir"
}

# PATH-shim a binary: records each invocation's args (one line per call) to
# $SHIM_DIR/<name>.calls, then runs the optional body ($2).
make_shim() {
    local name="$1" body="${2:-}"
    cat >"$SHIM_DIR/$name" <<SHIM
#!/usr/bin/env bash
echo "\$*" >>"$SHIM_DIR/$name.calls"
$body
SHIM
    chmod +x "$SHIM_DIR/$name"
}

shim_calls() { cat "$SHIM_DIR/$1.calls" 2>/dev/null; }
