// noise.ts — decide whether a changed path is noise (lockfile / minified /
// sourcemap / build output / generated / oversized / minified-by-content) and
// should be dropped BEFORE the diff is built, so generated bytes never reach
// the model prompt. Byte-for-byte port of fetch-diff.sh `noise_reason()`:
// the cases and their ORDER must match (a path can match several rules; the
// first wins), or a file's drop-reason changes across the migration.
//
// `readBlob`/`blobSize` are injected so tests can feed real fixture content
// without a git checkout, and so the production caller can route them through
// `git show <head>:<path>` / `git cat-file -s` exactly as the bash did.

/** Read the new-content blob for a path, or null when it doesn't exist at head (matches `git show` failing). */
export type ReadBlob = (path: string) => string | null;

/** Size in bytes of the new-content blob (O(1) via `git cat-file -s`); 0 when absent. */
export type BlobSize = (path: string) => number;

/** First-line marker scan window — fetch-diff.sh pipes the blob through `head -20`. */
const GENERATED_HEAD_LINES = 20;

/** Blob-size ceiling: a file over ~1MB is a dump/bundle/vendored blob — drop it. */
const LARGE_FILE_BYTES = 1_000_000;

/** A single line longer than this (UTF-8 BYTES) marks machine-generated/minified content. */
const MINIFIED_LINE_BYTES = 5000;

/**
 * Return the drop-reason for a noise path, or null when the file is real source
 * to review. Cases are evaluated in the SAME order as the bash `noise_reason()`:
 * lockfile → minified-ext → sourcemap → build-output → @generated marker →
 * large-file → minified-by-content. Path-pattern rules never read the blob;
 * the content rules only run once the cheap checks miss.
 */
export function noiseReason(path: string, readBlob: ReadBlob, blobSize: BlobSize): string | null {
  if (
    path.endsWith(".lock") ||
    path.endsWith("-lock.json") ||
    path.endsWith("/pnpm-lock.yaml") ||
    path === "pnpm-lock.yaml" ||
    path.endsWith("/bun.lockb") ||
    path === "bun.lockb"
  ) {
    return "lockfile";
  }
  if (path.endsWith(".min.js") || path.endsWith(".min.css")) {
    return "minified";
  }
  if (path.endsWith(".map")) {
    return "sourcemap";
  }
  if (isExtraLockfile(path)) {
    return "lockfile";
  }

  if (isVendored(path)) {
    return "vendored";
  }

  if (isBuildOutput(path)) {
    return "build-output";
  }

  if (isGeneratedCode(path)) {
    return "generated";
  }

  // @generated marker in the first lines of the new content. A missing blob
  // (readBlob → null) yields no marker, mirroring `git show` failing silently.
  const blob = readBlob(path);
  if (blob !== null) {
    const head = blob.split("\n", GENERATED_HEAD_LINES);
    if (head.some((line) => line.includes("@generated") || line.includes("DO NOT EDIT"))) {
      return "generated";
    }
  }

  // Oversized blob: caps the long-line scan below (anything reaching it is ≤1MB).
  if (blobSize(path) > LARGE_FILE_BYTES) {
    return "large-file";
  }

  // Minified-by-content: hash-named bundles slip past the extension/dir checks
  // but always carry a pathologically long line. Position-independent — any
  // line over the threshold marks the file machine-generated. Measured in UTF-8
  // BYTES (Buffer.byteLength), matching fetch-diff.sh's awk byte length — a
  // multibyte line at the JS-code-unit boundary would otherwise drop differently.
  if (
    blob !== null &&
    blob.split("\n").some((line) => Buffer.byteLength(line, "utf8") > MINIFIED_LINE_BYTES)
  ) {
    return "minified";
  }

  return null;
}

/**
 * Match the bash build-output globs (dist or build at the path root or any
 * mid-path segment, each requiring at least one segment after it). A trailing
 * `dist`/`build` directory name is NOT build-output, matching the glob's
 * required trailing-slash-star suffix.
 */
function isBuildOutput(path: string): boolean {
  return (
    /(^|\/)(dist|build|out|coverage|target|obj|\.next|\.nuxt|\.svelte-kit|\.nyc_output|__pycache__|\.venv|venv|\.terraform|\.idea)\/.+/.test(
      path,
    ) || path.endsWith(".pyc")
  );
}

/** path === name OR path ends with /name (root or any directory). */
function isNamed(path: string, name: string): boolean {
  return path === name || path.endsWith("/" + name);
}

/** Lockfiles whose names don't end in `.lock`/`-lock.json` (the inline check covers those). */
function isExtraLockfile(path: string): boolean {
  return (
    path.endsWith(".gradle.lockfile") ||
    isNamed(path, "go.sum") ||
    isNamed(path, "npm-shrinkwrap.json") ||
    isNamed(path, "packages.lock.json") ||
    isNamed(path, "Package.resolved") ||
    isNamed(path, ".terraform.lock.hcl")
  );
}

/** Vendored third-party dependency directories (not authored in this repo). */
function isVendored(path: string): boolean {
  return (
    /(^|\/)(node_modules|vendor|third_party|Pods|Carthage|bower_components)\//.test(path) ||
    /(^|\/)\.yarn\/(releases|plugins|unplugged)\//.test(path)
  );
}

/** Code emitted by a generator from a schema/IDL (protobuf, graphql-codegen, .NET, Dart, Go). */
function isGeneratedCode(path: string): boolean {
  // Each alternative carries its own leading "." so the intent is unambiguous: these
  // match a dotted suffix (".g.cs", ".pb.go", …), never a bare "...g.cs" tail like "config.cs".
  if (
    /(\.pb\.go|\.generated\.tsx?|\.designer\.cs|\.g\.cs|\.g\.dart|\.freezed\.dart|\.gr\.dart|\.bundle\.js|\.chunk\.js)$/.test(
      path,
    )
  ) {
    return true;
  }
  if (/_grpc\.pb\.go$/.test(path) || /_pb2\.pyi?$/.test(path) || /_pb2_grpc\.py$/.test(path)) {
    return true;
  }
  if (/Grpc\.(java|cs|ts|js)$/.test(path)) return true;
  if (/(^|\/)zz_generated_[^/]*\.go$/.test(path)) return true;
  return /(^|\/)__generated__\//.test(path);
}
