// AC-9: diff classification performs ZERO per-file git spawns (no `git show
// <ref>:<path>`, no `git cat-file -s <ref>:<path>`) and a bounded total spawn
// count, regardless of how many files changed. Verified with a PATH-shim spawn
// counter around the REAL git binary — no mocks; every git call underneath is
// the actual `git`, its output unmodified.
import { describe, it, expect, afterEach } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, chmodSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fetchDiff } from "@/git/diff.js";
import { git, setupGitRepo, writeFile, removeRepo } from "./helpers.js";

const ARG_SEP = "\x1f"; // unit separator — never appears in a path/argv we generate here

/** Resolve the real `git` binary BEFORE the shim dir is prepended to PATH. */
function resolveRealGit(): string {
  return execFileSync("bash", ["-c", "command -v git"], { encoding: "utf8" }).trim();
}

/** Write a PATH-shim `git` that logs every invocation's argv then execs the real git. */
function installGitShim(): { shimDir: string; logPath: string; originalPath: string } {
  const realGit = resolveRealGit();
  const shimDir = mkdtempSync(join(tmpdir(), "git-shim-"));
  const logPath = join(shimDir, "spawn.log");
  const script = `#!/usr/bin/env bash\nprintf '%s${ARG_SEP}' "$@" >> "${logPath}"\nprintf '\\n' >> "${logPath}"\nexec "${realGit}" "$@"\n`;
  const gitShimPath = join(shimDir, "git");
  writeFileSync(gitShimPath, script);
  chmodSync(gitShimPath, 0o755);
  const originalPath = process.env.PATH ?? "";
  process.env.PATH = `${shimDir}:${originalPath}`;
  return { shimDir, logPath, originalPath };
}

/** Parsed argv (excluding the trailing empty element from the trailing separator) per invocation. */
function readSpawnLog(logPath: string): string[][] {
  if (!existsSync(logPath)) return [];
  return readFileSync(logPath, "utf8")
    .split("\n")
    .filter((line) => line !== "")
    .map((line) => line.split(ARG_SEP).slice(0, -1));
}

const repos: string[] = [];
let restorePath: string | null = null;

afterEach(() => {
  for (const r of repos.splice(0)) removeRepo(r);
  if (restorePath !== null) {
    process.env.PATH = restorePath;
    restorePath = null;
  }
});

describe("fetchDiff — spawn count (AC-9)", () => {
  it("performs zero per-file git spawns and <=20 total subprocesses over 200 changed files", () => {
    const dir = setupGitRepo();
    repos.push(dir);
    git(dir, "checkout", "-b", "feature", "--quiet");

    // 196 ordinary files.
    for (let i = 0; i < 196; i++) {
      writeFile(dir, `src/pkg${i % 20}/file${i}.ts`, `export const value${i} = ${i};\n`);
    }
    // One @generated marker file.
    writeFile(dir, "sdk/client.gen.ts", "// @generated by codegen\nexport const x = 1;\n");
    // One hash-named minified file (long line, content-only classification).
    writeFile(dir, "web/assets/bundle-Ab12cd.js", `${"z".repeat(6000)}\nconsole.log(1);\n`);
    // One >1MB large file.
    const big = Array.from({ length: 120_000 }, (_, i) => `const v${i} = ${i};`).join("\n") + "\n";
    writeFile(dir, "data/dump.ts", big);
    // One lockfile.
    writeFile(dir, "package-lock.json", '{"lockfileVersion": 3}\n');

    git(dir, "add", "-A");
    git(dir, "commit", "-m", "200-file mixed change", "--quiet");

    const { logPath, originalPath } = installGitShim();
    restorePath = originalPath;
    // Fixture is committed above — reset the counter so setup spawns (which also
    // ran through the shim once PATH included it) never count against fetchDiff.
    writeFileSync(logPath, "");

    const r = fetchDiff({
      baseBranch: "main",
      githubBaseRef: "main",
      cwd: dir,
      maxFiles: 0,
      maxDiffLines: 80_000,
    });

    expect(r.total_files).toBe(200);
    expect(r.dropped_files.find((d) => d.path === "sdk/client.gen.ts")?.reason).toBe("generated");
    expect(r.dropped_files.find((d) => d.path === "web/assets/bundle-Ab12cd.js")?.reason).toBe(
      "minified",
    );
    expect(r.dropped_files.find((d) => d.path === "data/dump.ts")?.reason).toBe("large-file");
    expect(r.dropped_files.find((d) => d.path === "package-lock.json")?.reason).toBe("lockfile");

    const invocations = readSpawnLog(logPath);
    expect(invocations.length).toBeGreaterThan(0); // the shim actually intercepted calls

    // (a) zero per-file spawns.
    const perFileShow = invocations.filter((argv) => argv[0] === "show");
    expect(perFileShow).toEqual([]);
    const perFileCatFileSize = invocations.filter(
      (argv) => argv[0] === "cat-file" && argv[1] === "-s",
    );
    expect(perFileCatFileSize).toEqual([]);

    // The batched replacements DID run — proves the new code path was exercised,
    // not just trivially absent because nothing needed a blob read.
    expect(invocations.some((argv) => argv[0] === "cat-file" && argv[1] === "--batch-check")).toBe(
      true,
    );
    expect(invocations.some((argv) => argv[0] === "cat-file" && argv[1] === "--batch")).toBe(true);

    // (b) bounded total subprocess count, independent of file count.
    expect(invocations.length).toBeLessThanOrEqual(20);
  });
});
